language: node_js
node_js:
- 12.21.0

cache: npm

install:
  - yarn ci

script:
  - yarn test
  - yarn run build

deploy:
  provide: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: gh-pages
